name: TDS Cache Verification

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # We must create the file/folder BEFORE the cache step attempts to save it
      - name: Create Dummy Files
        run: |
          mkdir -p my_deps
          echo "priming-data" > my_deps/data.txt

      - name: Cache Dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: my_deps
          key: cache-403713e

      - name: prime-cache-403713e
        run: echo "Cache hit status is ${{ steps.cache-step.outputs.cache-hit }}"
